# data related
data_dir: ../data
audio_extensions:
  - .flac

train_annotation: ../jsons/train.json
valid_annotation: ../jsons/valid.json
test_annotation: ../jsons/test.json

# run options related
batch_size: 5