# basic configs
run_num: 0
result_dir: '../results/asr/'

# data related
data_dir: ../data
audio_extensions:
  - .flac

train_annotation: ../jsons/train.json
valid_annotation: ../jsons/valid.json
test_annotation: ../jsons/test.json

skip_data_preparation: false

# run options related
train_batch_size: 8
valid_batch_size: 8
test_batch_size: 1

shuffle: false

# tokenizer related
tokenizer_path: ../results/tokenizer/run_0/bpe_1000.model

# feature related
sample_rate: 16000
n_fft: 400
n_mels: 60
win_length: 400
hop_length: 200

# model related
n_conv: 3
conv_kernel_size: 10
conv_stride: 2
conv_padding: valid

n_sab: 10
attention_heads: 6
dense_units: 1000